name: core
description: A pure dart implementation consist of business logic 
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  rxdart: ^0.22.6

